import { Argv } from "yargs";
import path from "path";
import fs from "fs";

export const command = "generateConfig [args]";

export const desc = "generate an avalanche config";

// INCOMPLETE
// TODO: investigate if this can be generated by docs
export const builder = (yargs: Argv) =>
  yargs
    .usage("Usage: generateConfig [args")
    .options({
      file: {
        description: `Config file in json format`,
        type: "string",
      },
      apiAdminEnabled: {
        type: "boolean",
        description: `if enabled, expose the admin api`,
        default: false,
      },
      apiAuthRequired: {
        type: "boolean",
        description: `If enabled API calls require an authorization token`,
        default: false,
      },
      apiHealthEnabled: {
        type: "boolean",
        description: `if enabled, expose the health api`,
        default: true,
      },
    })
    .help("help")
    .alias("help", "h")
    .help();

export async function handler(args: any) {
  // TODO: complete
  console.log(`Feature incomplete for now`);
}
